export * as Route from './Route.vue'
export * as Certificate from './Certificate.vue'
export * as Dashboard from './Dashboard.vue'
export * as Gateway from './Gateway.vue'
export * as Plugin from './Plugin.vue'
export * as Service from './Service.vue'
export * as Upstream from './Upstream.vue'